export const FrenchModalBody = "Here's some text about the French grading system"
export const UIAAModalBody = "Here's some text about the UIAA grading system"
export const YDSModalBody = "Here's some text about the Yosemite Decimal grading system"
export const BritishTradModalBody = "Here's some text about the British Traditional grading system"
export const AustralianModalBody = "Here's some text about the Australian grading system"